server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/sis
    username: ${POSTGRES_USER:sisuser}
    password: ${POSTGRES_PASSWORD:sispass}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
springdoc:
  swagger-ui.path: /swagger-ui.html
auth:
  jwt:
    secret: ${JWT_SECRET:dev-local-secret}
    ttl-seconds: 7200
