version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sis}
      POSTGRES_USER: ${POSTGRES_USER:-sisuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sispass}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 20

  discovery:
    build: ./discovery
    ports: ["8761:8761"]

  config-server:
    build: ./config-server
    ports: ["8888:8888"]
    depends_on: [discovery]

  auth-service:
    build: ./auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-sis}
      POSTGRES_USER: ${POSTGRES_USER:-sisuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sispass}
      JWT_SECRET: ${JWT_SECRET:-dev-local-secret}
    ports: ["8081:8081"]
    depends_on: [postgres, discovery]

  student-service:
    build: ./student-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-sis}
      POSTGRES_USER: ${POSTGRES_USER:-sisuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sispass}
      JWT_SECRET: ${JWT_SECRET:-dev-local-secret}
    ports: ["8082:8082"]
    depends_on: [postgres, discovery]

  pass-service:
    build: ./pass-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-sis}
      POSTGRES_USER: ${POSTGRES_USER:-sisuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sispass}
      JWT_SECRET: ${JWT_SECRET:-dev-local-secret}
    ports: ["8083:8083"]
    depends_on: [postgres, discovery]

  faculty-service:
    build: ./faculty-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-sis}
      POSTGRES_USER: ${POSTGRES_USER:-sisuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sispass}
      JWT_SECRET: ${JWT_SECRET:-dev-local-secret}
    ports: ["8084:8084"]
    depends_on: [postgres, discovery]

  gateway:
    build: ./gateway
    environment:
      JWT_SECRET: ${JWT_SECRET:-dev-local-secret}
    ports: ["8080:8080"]
    depends_on: [auth-service, student-service, pass-service, faculty-service]
